# Logging
logging:
    level:
        root: INFO
        #        web: DEBUG
        com.tareqmy.springbootexamples: DEBUG


# Spring properties
spring:
    application:
        name: SpringBootExamples
    profiles:
        active: dev
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: password
        driverClassName: org.h2.Driver
        hikari:
            maximum-pool-size: 15
            minimum-idle: 5
            idle-timeout: 30000 #30 seconds
            connection-timeout: 10000 #10 seconds
            max-lifetime: 300000 #5 minutes
            pool-name: exampleHikariPool
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        open-in-view: false
    h2:
        console:
            enabled: true
            path: /h2/console
    task:
        execution:
            pool:
                core-size: 5
                max-size: 20
                queue-capacity: 10000
            thread-name-prefix: exampleExec-
        scheduling:
            pool:
                size: 5
            thread-name-prefix: exampleSchedule-


# App Properties
springbootexamples:
    app:
        jwtSecret: tareqmySecretKey
        jwtExpirationMs: 86400000
        securitySchemeKey: tareqmySchemeKey
    mail:
        host: localhost
        username:
        password:
        port: 1025
        protocol: smtp
        tls: false
        auth: false
        from: no-reply@springbootexamples.tareqmy.com


# Swagger properties
springdoc:
    swagger-ui:
        path: /api/open/swagger/ui.html
        enabled: true
    api-docs:
        path: /api/open/docs
        enabled: true
    show-actuator: true


# Management properties
management:
    endpoints:
        web:
            base-path: /api/actuator
            exposure:
                include: "*"
                exclude: caches, shutdown
        enabled-by-default: true
    info:
        git:
            enabled: true
