# Logging
logging:
    level:
        root: INFO
        #        web: DEBUG
        com.tareqmy.springbootexamples: DEBUG


# Spring properties
spring:
    application:
        name: SpringBootExamples
    profiles:
        active: dev
    datasource:
        url: jdbc:mariadb://localhost:3306/springbootexamplesdb
        username: dbadmin
        password: dbadmin
        driverClassName: org.mariadb.jdbc.Driver
        hikari:
            maximum-pool-size: 15
            minimum-idle: 5
            idle-timeout: 30000 #30 seconds
            connection-timeout: 10000 #10 seconds
            max-lifetime: 300000 #5 minutes
            pool-name: exampleHikariPool
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.MariaDB103Dialect
        open-in-view: false
    task:
        execution:
            pool:
                core-size: 5
                max-size: 20
                queue-capacity: 10000
            thread-name-prefix: exampleExec-
        scheduling:
            pool:
                size: 5
            thread-name-prefix: exampleSchedule-


# App Properties
springbootexamples:
    app:
        jwtSecret: tareqmySecretKey
        jwtExpirationMs: 86400000
        securitySchemeKey: tareqmySchemeKey
    mail:
        host: localhost
        username:
        password:
        port: 1025
        protocol: smtp
        tls: false
        auth: false
        from: no-reply@springbootexamples.tareqmy.com
    clientApp:
        name: sbeApp
    cors:
        allowed-origins: "http://localhost:8082"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count,X-${springbootexamples.clientApp.name}-alert,X-${springbootexamples.clientApp.name}-error,X-${springbootexamples.clientApp.name}-params"
        allow-credentials: true
        max-age: 1800


# Springdoc properties
springdoc:
    swagger-ui:
        path: /api/openapi/swagger/ui.html
        enabled: false
    api-docs:
        path: /api/openapi/docs
        enabled: true
    show-actuator: true


# Management properties
management:
    endpoints:
        web:
            base-path: /api/actuator
            exposure:
                include: "*"
                exclude: caches, shutdown
        enabled-by-default: true
    info:
        git:
            enabled: true
