version: '3.7'

services:
    sbedb:
        image: tareqmy/postgres:latest
        container_name: ${DATABASE}
        hostname: ${DATABASE}
        restart: unless-stopped
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        stdin_open: true
        volumes:
            - springbootexamples_pgdata:/var/lib/postgresql/data
            - springbootexamples_pgconf:/etc/postgresql
            - springbootexamples_pglog:/var/log/postgresql
        tty: true
        ports:
            - "5432:5432"
    sbemh:
        image: mailhog/mailhog:latest
        container_name: ${MAILHOG}
        hostname: ${MAILHOG}
        restart: unless-stopped
        ports:
            - "1025:1025"
            - "8025:8025"
volumes:
    springbootexamples_pgdata:
        driver: local
    springbootexamples_pgconf:
        driver: local
    springbootexamples_pglog:
        driver: local
