version: '3.7'

services:
    sbemh:
        image: mailhog/mailhog:latest
        container_name: ${MAILHOG}
        hostname: ${MAILHOG}
        restart: unless-stopped
        ports:
            - "1025:1025"
            - "8025:8025"
    sbedb:
        image: mariadb:latest
        container_name: ${DATABASE}
        hostname: ${DATABASE}
        restart: unless-stopped
        environment:
            - MARIADB_ROOT_PASSWORD=root
            - MARIADB_DATABASE=${DB_NAME}
            - MARIADB_USER=${DB_USER}
            - MARIADB_PASSWORD=${DB_PASS}
        volumes:
            - springbootexamples_mariadb_data:/var/lib/mysql
        ports:
            - "3306:3306"
    sbeapiui:
        image: swaggerapi/swagger-ui
        container_name: ${APIUI}
        hostname: ${APIUI}
        ports:
            - "8082:8080"
        environment:
            API_URL: "http://localhost:8080/api/openapi/docs"

volumes:
    springbootexamples_mariadb_data:
        driver: local
